src/SportsFinder/Controllers/FavoriteSportsController.cs
using System.Linq;
using Microsoft.AspNet.Mvc;
using SportsFinder.Models;
using System;
using System.Text.RegularExpressions;
using System.Security.Claims;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;

// For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860

namespace SportsFinder.Controllers
{
    public class FavoriteSportsController : Controller
    {
        // Dependency Injecting giving us the database context
        private ApplicationDbContext _context;
        private UserManager<ApplicationUser> _userManager;

        public FavoriteSportsController(ApplicationDbContext context, UserManager<ApplicationUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        // GET: /<controller>/
        public IActionResult Index()
        {
            System.Diagnostics.Debug.WriteLine("In Index");
            ViewData["User"] = _context.Users.First(u => u.Id == User.GetUserId());
            return View(_context.Sport.ToList());
        }

        public IActionResult Edit()
        {
            return View();
        }

        [HttpPost]
        public IActionResult SaveFavoriteSports(string data)
        {
            System.Diagnostics.Debug.WriteLine("List to save = " + data);

            string[] strarr = data.Split(',');
            string sportsList = "";

            Regex parser = new Regex(@"([a-z:A-Z:\s]+)");
            Match match = parser.Match(data);


            while (match.Success)
            {
                sportsList += match.Value + "|";
                match = match.NextMatch();
            }

            System.Diagnostics.Debug.WriteLine("List to save = " + sportsList);

            ApplicationUser user = _context.Users.First(u => u.Id == User.GetUserId());
            user.FavoriteSports = sportsList;
            _context.Update(user);
            _context.SaveChanges();

            return Json("Favorite Sports Saved!");
        }
    }
}

src/SportsFinder/Controllers/SportEventsController.cs
using System.Linq;
using Microsoft.AspNet.Mvc;
using Microsoft.AspNet.Mvc.Rendering;
using Microsoft.Data.Entity;
using SportsFinder.Models;
using System.Text.RegularExpressions;
using System;

namespace SportsFinder.Controllers
{
    public class SportEventsController : Controller
    {
        private ApplicationDbContext _context;
        
        public SportEventsController(ApplicationDbContext context)
        {
            _context = context;    
        }

        // GET: SportEvents
        public IActionResult Index(string searchString)
        {

            var sportEvent = from s in _context.SportEvent
                             select s;
            if (!string.IsNullOrEmpty(searchString))
            {
                sportEvent = sportEvent.Where(s => s.EventSport.Contains(searchString));

            }
            return View(sportEvent.ToList());
        }

        // GET: SportEvents/Details/5
        public IActionResult Details(int? id)
        {
            if (id == null)
            {
                return HttpNotFound();
            }

            SportEvent sportEvent = _context.SportEvent.Single(m => m.ID == id);
            if (sportEvent == null)
            {
                return HttpNotFound();
            }

            return View(sportEvent);
        }

        // GET: SportEvents/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: SportEvents/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(SportEvent sportEvent)
        {
            string[] arr = sportEvent.EquipmentList.Split(',');
            string newEqpList = "";
            for (int k = 0; k < arr.Length; k++)
            {
                string newStr = "";
                char[] charArr = arr[k].ToCharArray();
                if (charArr[0] == ' ')
                {
                    for (int i = 1; i < charArr.Length; i++)
                    {
                        newStr += charArr[i];
                    }
                    newEqpList += newStr;
                }else
                {
                    newEqpList += arr[k];
                }

                if (k != (arr.Length - 1))
                    newEqpList += ",";
            }

            sportEvent.EquipmentList = newEqpList;

            if (ModelState.IsValid)
            {
                var creator = User.Identity.Name;
                Console.Write(creator);
                SportEvent event1 = sportEvent;
                event1.EventCreator = creator;
                event1.RSVPList = creator + "|";
                _context.SportEvent.Add(event1);
                 
                
                _context.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(sportEvent);
        }

        // GET: SportEvents/Edit/5
        public IActionResult Edit(int? id)
        {
            if (id == null)
            {
                return HttpNotFound();
            }

            SportEvent sportEvent = _context.SportEvent.Single(m => m.ID == id);
            if (sportEvent == null)
            {
                return HttpNotFound();
            }
            return View(sportEvent);
        }

        // POST: SportEvents/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(SportEvent sportEvent)
        {
            if (ModelState.IsValid)
            {
                _context.Update(sportEvent);
                _context.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(sportEvent);
        }

        // GET: SportEvents/Delete/5
        [ActionName("Delete")]
        public IActionResult Delete(int? id)
        {
            if (id == null)
            {
                return HttpNotFound();
            }

            SportEvent sportEvent = _context.SportEvent.Single(m => m.ID == id);
            if (sportEvent == null)
            {
                return HttpNotFound();
            }

            return View(sportEvent);
        }

        // POST: SportEvents/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(int id)
        {
            SportEvent sportEvent = _context.SportEvent.Single(m => m.ID == id);
            _context.SportEvent.Remove(sportEvent);
            _context.SaveChanges();
            return RedirectToAction("Index");
        }

        [HttpPost]
        public IActionResult UpdateEquipmentList(string data, int eventId)
        {
            string broughtEquipmentList = "";

            System.Diagnostics.Debug.WriteLine("Value = " + data);

            Regex parser = new Regex(@"([a-z:A-z\s+]+):([a-z:A-Z]+@[a-z:A-Z]+\.[a-z:A-Z]+)");
            Match match = parser.Match(data);

            while (match.Success)
            {
                broughtEquipmentList += match.Value + "|";
                match = match.NextMatch();
            }

            SportEvent sportEvent = _context.SportEvent.Single(m => m.ID == eventId);
            sportEvent.EquipmentBeingBroughtList = broughtEquipmentList;
            _context.SaveChanges();

            return Json("This equipment is now marked as being brought by you!");
        }

        [HttpPost]
        public IActionResult AddUserToRsvpList(string userName, int eventId)
        {
            SportEvent sportEvent = _context.SportEvent.Single(m => m.ID == eventId);
            string currentRsvpList = "";

            if (sportEvent.RSVPList != null)
            {
                currentRsvpList += sportEvent.RSVPList;
            }

            currentRsvpList += userName + "|";

            sportEvent.RSVPList = currentRsvpList;
            sportEvent.PplAttendingCount++;
            _context.SaveChanges();

            return Json(userName + " you have been added to the RSVP list!");
        }
    }
}

src/SportsFinder/Controllers/SportsInfoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNet.Mvc;
using SportsFinder.Models;

// For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860

namespace SportsFinder.Controllers
{
    public class SportsInfoController : Controller
    {

        private ApplicationDbContext _context;

        public SportsInfoController(ApplicationDbContext context)
        {
            _context = context;
        }
        // GET: /<controller>/
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult BasketBall()
        {
            var sportEvent = from s in _context.SportEvent
                             select s;
            if (!String.IsNullOrEmpty("BasketBall"))
            {
                sportEvent = sportEvent.Where(s => s.EventSport.Contains("BasketBall"));

            }
            return View(sportEvent.ToList());
        }

        public IActionResult Baseball()
        {
            var sportEvent = from s in _context.SportEvent
                             select s;
            if (!String.IsNullOrEmpty("baseball"))
            {
                sportEvent = sportEvent.Where(s => s.EventSport.Contains("baseball"));

            }
            return View(sportEvent.ToList());
        }

        public IActionResult Soccer()
        {
            var sportEvent = from s in _context.SportEvent
                             select s;
            if (!String.IsNullOrEmpty("soccer"))
            {
                sportEvent = sportEvent.Where(s => s.EventSport.Contains("soccer"));

            }
            return View(sportEvent.ToList());
        }

        public IActionResult Hockey()
        {
            var sportEvent = from s in _context.SportEvent
                             select s;
            if (!String.IsNullOrEmpty("hockey"))
            {
                sportEvent = sportEvent.Where(s => s.EventSport.Contains("hockey"));

            }
            return View(sportEvent.ToList());
        }

        public IActionResult Cricket()
        {
            var sportEvent = from s in _context.SportEvent
                             select s;
            if (!String.IsNullOrEmpty("cricket"))
            {
                sportEvent = sportEvent.Where(s => s.EventSport.Contains("cricket"));

            }
            return View(sportEvent.ToList());
        }

        public IActionResult FrisbyGolf()
        {
            var sportEvent = from s in _context.SportEvent
                             select s;
            if (!String.IsNullOrEmpty("discgolf"))
            {
                sportEvent = sportEvent.Where(s => s.EventSport.Contains("discgolf"));

            }

            return View(sportEvent.ToList());
        }

        public IActionResult RockClimbing()
        {
            var sportEvent = from s in _context.SportEvent
                             select s;
            if (!String.IsNullOrEmpty("rockclimbing"))
            {
                sportEvent = sportEvent.Where(s => s.EventSport.Contains("rockclimbing"));

            }
            return View(sportEvent.ToList());
        }

        public IActionResult MountainBiking()
        {
            var sportEvent = from s in _context.SportEvent
                             select s;
            if (!String.IsNullOrEmpty("mountainbiking"))
            {
                sportEvent = sportEvent.Where(s => s.EventSport.Contains("mountainbiking"));

            }
            return View(sportEvent.ToList());
        }

        public IActionResult Skateboarding()
        {
            var sportEvent = from s in _context.SportEvent
                             select s;
            if (!String.IsNullOrEmpty("skateboarding"))
            {
                sportEvent = sportEvent.Where(s => s.EventSport.Contains("skateboarding"));

            }
            return View(sportEvent.ToList());
        }
    }
}

src/SportsFinder/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
    <head>

        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
        <script>
            $(document).ready(function () {
                $(".ssdi").mouseenter(function () {
                    $(this).animate({ left:'10px', height: '+=10px', width: '+=10px' });
                    $(this).css({ "background-color": "#b3b3b3", "font-size": "200%" })

                });
                $(".ssdi").mouseleave(function () {
                    $(this).animate({ height: '-=10px', width: '-=10px' });
                    $(this).css({ "background-color": " #000000", "font-size": "100%" })

                });

            });
        </script>

        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>@ViewData["Title"] - Sports Finder</title>

        <environment names="Development">
            <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
            <link rel="stylesheet" href="~/css/site.css" />
        </environment>
        <environment names="Staging,Production">
            <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.5/css/bootstrap.min.css"
                  asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
                  asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
            <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
        </environment>
    </head>
    <body>

        @{
            if (User.Identity.Name != null)
            {
                <div id="sidebar-wrapper" style="width: 20%; padding: 10px; float: left">
                    <ul class="sidebar-nav">
                        <li class="sidebar-brand">
                            <a>
                                Sports
                            </a>
                        </li>
                        <li class="ssdi">
                            <a asp-controller="SportsInfo" asp-action="Basketball">BasketBall</a>
                        </li>
                        <li class="ssdi"> 
                            <a asp-controller="SportsInfo" asp-action="Baseball">Baseball</a>
                        </li>
                        <li class="ssdi">
                            <a asp-controller="SportsInfo" asp-action="Soccer">Soccer</a>
                        </li>
                        <li class="ssdi">
                            <a asp-controller="SportsInfo" asp-action="Hockey">Hockey</a>
                        </li>
                        <li class="ssdi">
                            <a asp-controller="SportsInfo" asp-action="Cricket">Cricket</a>
                        </li>
                        <li class="ssdi">
                            <a asp-controller="SportsInfo" asp-action="FrisbyGolf">Disc Golf</a>
                        </li>
                        <li class="ssdi">
                            <a asp-controller="SportsInfo" asp-action="RockClimbing">Rock Climbing</a>
                        </li>
                        <li class="ssdi">
                            <a asp-controller="SportsInfo" asp-action="MountainBiking">Mountain Biking</a>
                        </li>
                        <li class="ssdi">
                            <a asp-controller="SportsInfo" asp-action="Skateboarding">Skateboarding</a>
                        </li>
                    </ul>
                </div>
            }
        }        
            <div class="navbar navbar-inverse navbar-fixed-top">
                <div class="container">
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                            <span class="sr-only">Toggle navigation</span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                        <a asp-controller="Home" asp-action="Index" class="navbar-brand">Sports Finder</a>
                    </div>
                    <div class="navbar-collapse collapse">
                        <ul class="nav navbar-nav">
                            <li><a asp-controller="Home" asp-action="About">About</a></li>
                            <li><a asp-controller="Home" asp-action="Contact">Contact</a></li>
                            @{
                                if (User.Identity.Name != null)
                                {
                                    <li><a asp-controller="FavoriteSports" asp-action="Index">Favorite Sports</a></li>
                                    <li><a asp-controller="SportEvents" asp-action="Index">Events</a></li>
                                }
                            }
                        </ul>
                        @await Html.PartialAsync("_LoginPartial")
                    </div>
                </div>
            </div>
        <div id="page-content-wrapper">
            <div class="container body-content" style="margin-left: 20%">
                @RenderBody()
                <hr />
                <footer>
                    <p>&copy; Sports Finder | Group Tunguska | SSDI Project 2016 - Brad Neil Hardik Gabriel</p>
                </footer>
            </div>
        </div>

            <environment names="Development">
                <script src="~/lib/jquery/dist/jquery.js"></script>
                <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
                <script src="~/js/site.js" asp-append-version="true"></script>
            </environment>
            <environment names="Staging,Production">
                <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.1.4.min.js"
                        asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                        asp-fallback-test="window.jQuery">
                </script>
                <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.5/bootstrap.min.js"
                        asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                        asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal">
                </script>
                <script src="~/js/site.min.js" asp-append-version="true"></script>
            </environment>

            @RenderSection("scripts", required: false)
</body>
</html>