src/SportsFinder/Controllers/EventPageController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNet.Mvc;
using SportsFinder.Models;

// For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860

namespace SportsFinder.Controllers
{
    public class EventPageController : Controller
    {
        // Dependency Injecting giving us the database context
        private ApplicationDbContext _context;

        public EventPageController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: /<controller>/
        public IActionResult Index()
        {
            return View(_context.Sport);
        }
    }
}

src/SportsFinder/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNet.Mvc;
using SportsFinder.Models;

namespace SportsFinder.Controllers
{
    public class HomeController : Controller
    {
        private ApplicationDbContext _context;

        public HomeController(ApplicationDbContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            return View(_context.SportEvent.ToList());
        }

        public IActionResult About()
        {
            ViewData["Message"] = "SportsFinder is dedicated to helping you find fellow sports enthusiasts near you, letting find an event in your neighbourhood when you're in the mood for sport.";

            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Created by James Stell, Thomas Neil K, Hardik Thakkar & Gabriel Stevens";

            return View();
        }


        public IActionResult UserProfile()
        {
            return View();
        }

        public IActionResult Error()
        {
            return View();
        }
    }
}

src/SportsFinder/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"] Sports Finder</h2>
<div class="container">
    <p class="col-md-10">
        Sports Finder is dedicated to helping you find fellow sports enthusiasts near you. It lets you find a sport
        event in your neighborhood when you are in the mood to play a sport, yet don't have anyone to play with.
    </p>    
</div>
<div class="container">
    <p><i>Created as part of the SSDI Group Project for Spring 2016</i></p>
</div>
<div class="container">
    <h2><i>Example</i> Sport Events Data</h2>
</div>
<div id="map-canvas" style="width: 600px; height: 600px"></div>

<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAG8diNyE5CdFVLOvf9u7NlVoi6aEk8SH8"></script>
<script type="text/javascript">

    var map;
    var infoWindow;
    var sportList = [
        "Baseball!",
        "Basketball!",
        "Soccer!",
        "Hockey!",
        "Cricket!",
        "Disc Golf!",
        "Rock Climbing!",
        "Mountain Biking!",
        "Skateboarding!"
    ]

    function initialize() {



        // Get current location for simulation
        if (navigator.geolocation) {
            navigator.geolocation.getCurrentPosition(function (position) {
                var pos = {
                    lat: position.coords.latitude,
                    lng: position.coords.longitude
                };

                var mapOptions = {
                    zoom: 12,
                    center: pos,
                    mapTypeId: google.maps.MapTypeId.ROADMAP
                };

                map = new google.maps.Map(document.getElementById("map-canvas"), mapOptions);
                infoWindow = new google.maps.InfoWindow({ map: map });                

                for (var i = 0; i < 15; i++) {
                    var marker = new google.maps.Marker({
                        position: { lat: pos.lat - (Math.random() * (.1 - .00001)), lng: pos.lng - (Math.random() * (.1 - .00001)) },
                        map: map,
                        title: sportList[Math.floor(Math.random() * (8 - 0) + 0)]
                    });
                    var marker2 = new google.maps.Marker({
                        position: { lat: pos.lat + (Math.random() * (.1 - .00001)), lng: pos.lng + (Math.random() * (.1 - .00001)) },
                        map: map,
                        title: sportList[Math.floor(Math.random() * (8 - 0) + 0)]
                    });
                }

                infoWindow.setPosition(pos);
                infoWindow.setContent('Your Location');

            }, function () {
                handleLocationError(true, infoWindow, map.getCenter());
            });
        }

            // If current location isn't available
        else {
            var pos = new google.maps.LatLng(35.2033533, -80.9796095); // Charlotte

            var mapOptions = {
                zoom: 12,
                center: pos,
                mapTypeId: google.maps.MapTypeId.ROADMAP
            };

            map = new google.maps.Map(document.getElementById("map-canvas"), mapOptions);
            infoWindow = new google.maps.InfoWindow({ map: map });

            for (var i = 0; i < 15; i++) {
                var marker = new google.maps.Marker({
                    position: { lat: pos.lat - (Math.random() * (.1 - .00001)), lng: pos.lng - (Math.random() * (.1 - .00001)) },
                    map: map,
                    title: sportList[Math.floor(Math.random() * (8 - 0) + 0)]
                });
                var marker2 = new google.maps.Marker({
                    position: { lat: pos.lat + (Math.random() * (.1 - .00001)), lng: pos.lng + (Math.random() * (.1 - .00001)) },
                    map: map,
                    title: sportList[Math.floor(Math.random() * (8 - 0) + 0)]
                });
            }

            infoWindow.setPosition(pos);
            infoWindow.setContent('Your Location');
        }
    }

    google.maps.event.addDomListener(window, 'load', initialize);
</script>

src/SportsFinder/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Developer Contact Information";
}
<h2>@ViewData["Title"]</h2>

<h4>Developer Emails</h4>
<div class="dl-horizontal">
    <dt>
        Brad Stell
    </dt>
    <dd>
        jstell@uncc.edu
    </dd>
    <dt>
        Hardik Thakkar
    </dt>
    <dd>
        hthakkar@uncc.edu
    </dd>
    <dt>
        Niel Alex
    </dt>
    <dd>
        tkattamp@uncc.edu
    </dd>
    <dt>
        Gabriel Stevens
    </dt>
    <dd>
        gsteven4@uncc.edu
    </dd>
</div>



@*<div class="container">
    <h1>Emails</h1>
    <p>Brad Stell: jstell@uncc.edu</p>
    <p>hardik thakkar : hthakkar@uncc.edu</p>
    <p>Gabriel Stevens: gsteven4@uncc.edu</p>
    <p>Niel Alex: tkattamp@uncc.edu</p>
</div>*@

src/SportsFinder/Views/Home/Index.cshtml
@model IEnumerable<SportsFinder.Models.SportEvent>

@{
    ViewData["Title"] = "Home Page";
}
<script src="~/js/GoogleMaps.js"></script>
    
<div id="myCarousel" class="carousel slide" data-ride="carousel" data-interval="6000">
    <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
    </ol>
    <div class="carousel-inner" role="listbox">
        <div class="item active">
            <img src="~/images/ASP-NET-Banners-01.png" alt="ASP.NET" class="img-responsive" />
            <div class="carousel-caption">
            </div>
        </div>
        <div class="item">
            <img src="~/images/ASP-NET-Banners-02.png" alt="Package Management" class="img-responsive" />
            <div class="carousel-caption">
                <p>
                    Start an event, choose the location, specify what gear is needed, publish and go play!
                    <a class="btn btn-default btn-default" asp-controller="EventPage" asp-action="Index">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
    </div>
    <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>

<div class="col-md-12">
    <h1>Sports Finder</h1>
    <h3>Multiplayer Sports</h3>
    <p>
        Do you ever find youself wishing you had a bunch of people to play sports with? Are your friends
        lazy? Do you want new friends who are more active? Sports Finder is here for you! Sports Finder 
        will help you find people to play sports with. You can browse by sport, search for events in your area,
        and go play sports!
    </p>
    <h3>Solo Sports</h3>
    <p>
        Don't play well with others? Sports Finder can help you play by yourself too. Just search for the sport
        you are interested in and we will show you on a map where you can do that sport. 
    </p>
</div>

<div class="col-md-12">
    <script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAG8diNyE5CdFVLOvf9u7NlVoi6aEk8SH8"></script>
    <script type="text/javascript">

        var map;

        function initialize() {                      

            if (navigator.geolocation) {
                navigator.geolocation.getCurrentPosition(function (position) {
                    var pos = {
                        lat: position.coords.latitude,
                        lng: position.coords.longitude
                    };

                    var mapOptions = {
                        zoom: 11,
                        center: pos,
                        mapTypeId: google.maps.MapTypeId.ROADMAP
                    };

                    map = new google.maps.Map(document.getElementById("map-canvas"), mapOptions);
                    infoWindow = new google.maps.InfoWindow({ map: map });

                    infoWindow.setPosition(pos);
                    infoWindow.setContent('Your Location');

                    @foreach (var item in Model)
                    {
                        <text>

                        var latLng = new google.maps.LatLng(@(item.Latitude), @(item.Longitude));

                        var marker = new google.maps.Marker({                        
                            position: latLng,
                            map: map,
                            title: "@(item.EventSport)"
                        });

                        </text>
                    }

                }, function () {
                    handleLocationError(true, infoWindow, map.getCenter());
                });
            }
            
            else {

                var pos = {
                    lat: 35.234385,
                    lng: -80.847297
                };

                var mapOptions = {
                    zoom: 11,
                    center: pos,
                    mapTypeId: google.maps.MapTypeId.ROADMAP
                };

                map = new google.maps.Map(document.getElementById("map-canvas"), mapOptions);

                @foreach (var item in Model)
                {
                    <text>

                    var latLng = new google.maps.LatLng(@(item.Latitude), @(item.Longitude));

                    var marker = new google.maps.Marker({                        
                        position: latLng,
                        map: map,
                        title: '@(item.EventSport)'
                    });

                    </text>
                }
            }
        }

        google.maps.event.addDomListener(window, 'load', initialize);
    </script>

    @{
        if (User.Identity.Name != null)
        {
            <div class="container">
                <h2>Sports in Your Area</h2>
            </div>
            <div id="map-canvas" style="width: 600px; height: 600px"></div>
        }
    }
</div>